# Generated by Django 5.2.17 on 2026-08-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('customer_type', models.CharField(choices=[('regular', 'Regular'), ('wholesale', 'Wholesale'), ('new_customer', 'New Customer')], default='regular', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
