# Generated by Django 5.2.17 on 2026-08-29 08:25

from django.db import migrations

def migrate_to_multi_item(apps, schema_editor):
    Order = apps.get_model('Admin', 'Order')
    OrderItem = apps.get_model('Admin', 'OrderItem')
    Invoice = apps.get_model('Admin', 'Invoice')
    InvoiceItem = apps.get_model('Admin', 'InvoiceItem')

    for order in Order.objects.all():
        if order.chicken_type and order.weight:
            # Create the operational OrderItem
            order_item = OrderItem.objects.create(
                order=order,
                chicken_type=order.chicken_type,
                weight=order.weight
            )

            # Check if this order has an associated invoice
            try:
                invoice = order.invoice
                
                # Update GST on invoice
                if invoice.gst_amount is not None:
                    invoice.gst_type = 'fixed'
                    invoice.gst_input = invoice.gst_amount
                    invoice.calculated_gst_amount = invoice.gst_amount
                    invoice.save()

                # Create the financial InvoiceItem snapshot
                if invoice.selling_price_per_kg is not None:
                    InvoiceItem.objects.create(
                        invoice=invoice,
                        order_item=order_item,
                        chicken_type_snapshot=order.chicken_type,
                        weight_snapshot=order.weight,
                        selling_price_per_kg_snapshot=invoice.selling_price_per_kg
                    )
            except Exception: # Handle RelatedObjectDoesNotExist
                pass

def reverse_migration(apps, schema_editor):
    OrderItem = apps.get_model('Admin', 'OrderItem')
    InvoiceItem = apps.get_model('Admin', 'InvoiceItem')
    
    OrderItem.objects.all().delete()
    InvoiceItem.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_invoice_calculated_gst_amount_invoice_gst_input_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_to_multi_item, reverse_migration),
    ]
