# Generated by Django 5.2.17 on 2026-08-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_migrate_order_items_and_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
