# Generated by Django 5.2.17 on 2026-09-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_order_cutting_notes_order_meat_delivered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='meat_delivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='received_quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='waste_quantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='meat_delivered',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='received_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='waste_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
